#!/usr/bin/env python3

from glumpy import app, gloo, gl
import numpy as np
import cv2
from utils.detect import get_face, get_marks
from utils.shaders import img_vertex, img_fragment

vertex = """
attribute vec2 position;
void main(){
    gl_Position = vec4(position, 0.0, 1.0);
}"""
frag = """
void main(){ gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0); }"""

win = app.Window(color=(1,1,1,1))
brow1 = gloo.Program(vertex, frag, count=5)
brow2 = gloo.Program(vertex, frag, count=5)
eye1 = gloo.Program(vertex, frag, count=6)
eye2 = gloo.Program(vertex, frag, count=6)
nose1 = gloo.Program(vertex, frag, count=4)
nose2 = gloo.Program(vertex, frag, count=5)
lip1 = gloo.Program(vertex, frag, count=12)
lip2 = gloo.Program(vertex, frag, count=8)
jaw = gloo.Program(vertex, frag, count=17)

quad = gloo.Program(img_vertex, img_fragment, count=4)
quad['position'] = [(-0.6,-1), (-1,-1), (-0.6,-0.6), (-1,-0.6)]
quad['texcoord'] = [( 0, 1), ( 1, 1), ( 0, 0), ( 1, 0)]
gl.glLineWidth(1.5)

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_POS_MSEC, 50)
face_coord = None
while face_coord is None:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face_coord = get_face(gray)

@win.event
def on_draw(dt):
    global face_coord, cap
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    new_face = get_face(gray)
    face_coord = face_coord if new_face is None else new_face
    marks = get_marks(gray, face_coord)*-1
    brow1['position'] = marks[17:22]
    brow2['position'] = marks[22:27]
    eye1['position'] = marks[36:42]
    eye2['position'] = marks[42:48]
    nose1['position'] = marks[27:31]
    nose2['position'] = marks[31:36]
    lip1['position'] = marks[48:60]
    lip2['position'] = marks[60:68]
    jaw['position'] = marks[0:17]
    img = frame[face_coord.top()-20:face_coord.bottom()+20, face_coord.left()-10:face_coord.right()+10]
    img = cv2.cvtColor(cv2.resize(img, (100,100)), cv2.COLOR_BGR2RGB)
    quad['texture'] = img
    win.clear()
    brow1.draw(gl.GL_LINE_LOOP)
    brow2.draw(gl.GL_LINE_LOOP)
    eye1.draw(gl.GL_LINE_LOOP)
    eye2.draw(gl.GL_LINE_LOOP)
    nose1.draw(gl.GL_LINE_STRIP)
    nose2.draw(gl.GL_LINE_LOOP)
    lip1.draw(gl.GL_LINE_LOOP)
    lip2.draw(gl.GL_LINE_LOOP)
    jaw.draw(gl.GL_LINE_STRIP)
    quad.draw(gl.GL_TRIANGLE_STRIP)


app.run(framerate=20)
cap.release()
